import {
  contactPortals,
  customerPortals,
  customerTicketPortals,
  downloads,
  newsItems,
  partnerPortals,
  products,
  projects,
  services,
  tools,
} from "@/lib/site-data";

export const staticRoutes = [
  "/",
  "/about/",
  "/business/c/",
  "/business/c/need.html",
  "/business/index.html",
  "/business/product/index.html",
  "/business/product/software/index.html",
  "/business/product/software/educheck/index.html",
  "/business/product/hardware/index.html",
  "/business/product/cloud/index.html",
  "/business/services/index.html",
  "/business/services/b/",
  "/business/services/b/index.html",
  "/business/services/b/order.html",
  "/business/services/b/sc.html",
  "/business/services/b/htc-ihaikou.html",
  "/business/services/b/hnhsd-vmh3c.html",
  "/business/services/p/",
  "/business/services/p/index.html",
  "/business/services/p/oa.html",
  "/business/services/p/agent-orders.html",
  "/business/services/p/agent_info_maintenance.html",
  "/business/services/p/agent_register.html",
  "/business/services/p/agent_registers.html",
  "/business/services/c/",
  "/business/services/c/index.html",
  "/business/services/c/need.html",
  "/business/services/c/order.html",
  "/business/services/c/subscription.html",
  "/business/services/c/wo.html",
  "/business/services/c/wosu.html",
  "/business/services/c/customer-info.html",
  "/business/services/c/join.html",
  "/business/services/c/joins.html",
  "/business/services/c/needs.html",
  "/business/services/c/wosus.html",
  "/business/services/g/",
  "/business/services/g/index.html",
  "/business/services/g/base64.html",
  "/business/services/g/dns-query.html",
  "/business/services/g/sjdm.html",
  "/business/services/g/uuid.html",
  "/business/services/g/md5check.html",
  "/business/services/g/gemini/index.html",
  "/projects/",
  "/partners/",
  "/contact/",
  "/services/",
  "/products/",
  "/news/",
  "/company/timeline/",
  "/company/leadership/",
  "/tools/",
  "/downloads/",
  "/careers/",
  "/careers/cn/",
  "/careers/cn/index.html",
  "/careers/cn/team.html",
  "/careers/cn/life-at-xsec.html",
  "/careers/cn/work-at-xsec.html",
  "/careers/team/",
  "/careers/life/",
  "/careers/open-roles/",
  "/leadership/",
  "/leadership/index.html",
  "/leadership/me/",
  "/leadership/me/index.html",
  "/leadership/me/lead/",
  "/leadership/me/lead/index.html",
  "/leadership/fzlc/",
  "/leadership/fzlc/index.html",
  "/leadership/teams/qgyw/",
  "/leadership/teams/qgyw/index.html",
  "/leadership/pages/2025/finance_q2.html",
  "/legal/privacy/",
  "/legal/privacy/index.html",
  "/source/ztsm/",
  "/source/ztsm/index.html",
  "/source/ssrc/cf-sec-hn-cn/",
  "/source/ssrc/cf-sec-hn-cn/index.html",
];

export const dynamicRoutes = [
  ...projects.map((item) => item.href),
  ...newsItems.map((item) => item.href),
  ...services.map((item) => item.href),
  ...products.map((item) => item.href),
  ...tools.map((item) => item.href),
  ...downloads.map((item) => item.href),
  ...contactPortals.map((item) => item.href),
  ...customerPortals.map((item) => item.href),
  ...customerTicketPortals.map((item) => item.href),
  ...partnerPortals.map((item) => item.href),
];

export const allRoutes = [...staticRoutes, ...dynamicRoutes];
